name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        puppet:
          - "~> 7.0"
          - "~> 6.0"
          - "https://github.com/puppetlabs/puppet.git#main"
        exclude:
          - ruby: "2.6"
            puppet: "~> 7.0"
          - ruby: "2.5"
            puppet: "~> 7.0"

          - ruby: "3.1"
            puppet: "~> 6.0"
          - ruby: "3.0"
            puppet: "~> 6.0"

          - ruby: "2.6"
            puppet: "https://github.com/puppetlabs/puppet.git#main"
          - ruby: "2.5"
            puppet: "https://github.com/puppetlabs/puppet.git#main"
    env:
      BUNDLE_WITHOUT: release
      PUPPET_VERSION: ${{ matrix.puppet }}
    name: "Ruby ${{ matrix.ruby }} - Puppet ${{ matrix.puppet }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install expect
        run: sudo apt-get install expect
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build gem
        run: gem build *.gemspec
      - name: Run tests
        run: bundle exec cucumber -f progress
